site_name: Pointslocal Gameplan
site_url: http://corporate.pointslocal.com
site_description: API Documentation for Pointslocal's GamePlan
site_author: Nathan Kozyra

pages:
- Home: index.md
- Games: API_Games.md
- Players: API_Players.md
- Schools: API_Schools.md
- Teams: API_Teams.md
- Sports: API_Sports.md
- Standings: API_Standings.md