site_name: Pointslocal GamePlan API
site_url: http://corporate.pointslocal.com
site_description: API Documentation for Pointslocal's GamePlan
site_author: Nathan Kozyra

repo_url: https://github.com/pointslocal/gameplan-docs

pages:
- Home: index.md
- Games: API_Games.md
- Players: API_Players.md
- Schools: API_Schools.md
- Teams: API_Teams.md
- Sports: API_Sports.md
- Standings: API_Standings.md

copyright: Copyright &copy; 2015 Pointslocal.